[package]
name = "galg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.7.1"
# exe only depends follow...
anyhow = "1.0.63"
argh = "0.1.8"


